### ISSUE TITLE
Add CI build service integration

### ISSUE THREAD

**Issue by peter279k** [phpwatch/docker-php#1]
As title, we can consider integrating the CI building service.

And it can make sure the `Dockerfile` are reliable and verified :).

Here are some available CI build services we can consider:

- Travis CI
- Circle CI
- GitHub Actions

Most of repositories use the Travis CI on this GitHub org, but the GitHub Actions are also a good tool and it's official support on GitHub.

@Ayesh, do you have any idea about this :)? And do you have any preference about CI building service?

Once this issue is accepted, I'm happy to work on this.

**Comment by Ayesh** [comment]
Hi @peter279k - thank you for opening this issue. This repo is linked to docker hub as a free public build, and Docker Hub is already setup to rebuild on every push. My sole use case is to use this Docker image in Gitlab CI. It's quicker to run because all dependencies are baked in, thus helps me to keep myself within the free 2,000 minute limit Gitlab has. 

I doubt this docker image will serve any meaningful purpose to anyone else but me :) I would recommend builds from wodby or even the official PHP images themselves as they are kept up to date and automated. 

Thanks a lot for your interest @peter279k. I don't really think it would be a good use of your time to improve this repo because there are much better maintained repos out there.
